### ISSUE TITLE
Is cron like scheduling possible?

### ISSUE THREAD

**Issue by singhkays** [cncf/wg-serverless-workflow#31]
**What is the question**:

_Continuing the issue from previous repo https://github.com/cncf/wg-serverless/issues/245_ 

**Original Question**
I've been reviewing the spec and it seems like you can define the state/task start kind to be scheduled but this only takes an interval as a property. Is it possible to specify a cron like syntax?

**Example**
From Wikipedia https://en.wikipedia.org/wiki/Cron
```
This example runs a shell program called export_dump.sh at 23:45 (11:45 PM) every Saturday.

45 23 * * 6 /home/oracle/scripts/export_dump.sh

```

@tsurdilo Added an expected cron example above that I'm trying to figure out if it's supported.

**Comment by tsurdilo** [comment]
@singhkays Looking into how we can add that now and will submit a PR for you to review. 
The scheduled start was originally meant to describe a time interval during which workflow instantiation is possible. So to give an example, let's say we have a workflow that orchestrates our car auction bits, and this auction runs Mon-Fri 9am to 5pm only. Bids should not be able to be made (no workflow instances shall be created) outside of this defined ("scheduled") time.

It is not meant as in "create an instance of this workflow every Sunday at 3pm because workflow instances in most cases are triggered by consumed events. Is this the feature you were looking for? If so I think yes this would be a valid feature to add, just need to make sure it is what you need?

I think either way, if we kept the current description of scheduled start using both the ISO 8601 or a cron-line definition can be used and I will definitely add that. If the request is to add a cron-based trigger like ability, I think this is very interesting as well, so let me know. Thanks!

**Comment by singhkays** [comment]
@tsurdilo You're correct! the request is for a cron-based trigger like ability (cron syntax would be perfect if possible!) 

I've reviewed auction bid example and the current implementation makes sense as well :)

**Comment by tsurdilo** [comment]
@singhkays thanks for the explanation! 
For event based triggering we have to restrict that Event states cannot be the workflow starting states (as they wait for events to trigger workflow instance creation). Just making sure you are OK with that.
Second thing I wanted to get your opinion on is the naming convention. Currently we use 
"scheduled" which we explain in the spec. For cron-based triggered execution what would you call the execution type, maybe like "timed" or "triggered"? Looking for suggestions really for both. Thanks.

**Comment by singhkays** [comment]
@tsurdilo Re: restricting event state - I would like to think through that more. Here's a scenario where a restriction like that might pose a problem. 

**Example:** I use Github Actions cron schedule to build this docker image https://github.com/singhkays/docker-ffmpeg-av1-libaom every Sunday. Assume this is represented by a workflow that is triggered on a schedule. But sometimes, I may want to get the build the latest build ad-hoc within the week. I would think some UI will allow me to click a button that emits an event to trigger this build workflow. Now if the workflow restricts event states, is there another mechanism in the workflow spec which will allow such ad-hoc invocations? 

Re: Naming - I had assumed "scheduled" meant cron :) until I read further about specifying intervals in ISO8601 format. If we don't want to reuse the same name, "recurring" could be a good choice.

**Comment by tsurdilo** [comment]
@singhkays 
1) In my opinion instances of workflows that are triggered by event occurrence (and thus includes a temporal aspect to it) should only be able to be created by that (the occurrence of these events). This is both for "default" event start states as well as "scheduled" event start states.

Instances of workflow that are "default", "triggered", or "scheduled"  (not event-based starting state) should be able to be created outside of the defined interval or timed exec definition (cron). In those cases it would make sense to be able to do what you describe.

I don't think it makes sense to add multiple starting states each defining its own instantiation definition. At that point I think multiple separate workflows would be better suited. wdyt?

I can add this to the specification doc to make it clearer to readers. Hope this helps.

2) Sounds good to me. In the PR i called it "triggered". So we have "scheduled" via time interval and "triggered" via cron def. Wdyt? Would you like to use scheduled and recurring instead?

**Comment by tsurdilo** [comment]
@singhkays please see the latest updates and comments on https://github.com/cncf/wg-serverless-workflow/pull/34

**Comment by tsurdilo** [comment]
closed by https://github.com/cncf/wg-serverless-workflow/commit/c4eb8072511e2714e398db6b7f7d9890b4a40f9f
